extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  zipkin:

processors:
  batch:

exporters:
  debug:
#     verbosity: detailed
  otlp:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
  loki:
    endpoint: "${LOKI_ENDPOINT}"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:
        - otlp
        - zipkin
      processors: [batch]
      exporters:
        - debug 
        - otlp
    metrics:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - debug 
        - prometheus
    logs:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - debug 
        - loki
  extensions:
    - health_check
    - zpages